/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mes_devis (void);
GtkWidget* create_mes_devis_vol (void);
GtkWidget* create_mes_devis_hebergement (void);
GtkWidget* create_mes_devis_location (void);
GtkWidget* create_fenetre_paiement_vol (void);
GtkWidget* create_fenetre_validation (void);
GtkWidget* create_acceuil_client (void);
GtkWidget* create_mon_profile (void);
GtkWidget* create_acceuil_employee (void);
GtkWidget* create_acceuil_admin (void);
GtkWidget* create_fenetre_paiement_hebergement (void);
GtkWidget* create_fenetre_paiement_location (void);
GtkWidget* create_fenetre_entrer_n_d_v (void);
GtkWidget* create_fenetre_entrer_n_d_h (void);
GtkWidget* create_fenetre_entrer_n_d_l (void);
GtkWidget* create_gestion_devis_fact (void);
GtkWidget* create_gestion_devis_vol (void);
GtkWidget* create_gestion_devis_hebergement (void);
GtkWidget* create_gestion_devis_location (void);
