/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_gestion_voiture (void);
GtkWidget* create_window_ajouter_voiture (void);
GtkWidget* create_window_supprimer_voiture (void);
GtkWidget* create_window_recherche_voiture (void);
