/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *acceuil_client;
  GtkWidget *mes_devis_vol;
  GtkWidget *mes_devis_hebergement;
  GtkWidget *mes_devis_location;
  GtkWidget *acceuil_admin;
  GtkWidget *acceuil_employee;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  acceuil_client = create_acceuil_client (); 
gtk_widget_show (acceuil_client);
acceuil_admin = create_acceuil_admin (); 
gtk_widget_show (acceuil_admin);

  gtk_main ();
  return 0;
}

